### ISSUE TITLE
Inventory side issue

### ISSUE THREAD

**Issue by Ashu69Dev** [rumaier/r_bridge#1]
![Screenshot (4)](https://github.com/user-attachments/assets/9b9dc1ed-dcd1-4d14-b523-66431a77d2a7)
![Screenshot (5)](https://github.com/user-attachments/assets/76805fbc-86b9-471a-82f8-dbfc16652ea6)
[  script:r_moneywash] r_moneywash:getPlayerCooldown
[  script:r_moneywash] SCRIPT ERROR: @r_moneywash/src/server/main.lua:9: attempt to index a nil value (field 'Inventory')
[  script:r_moneywash] > callbackResponse (@ox_lib/imports/callback/server.lua:79)
[  script:r_moneywash] > handler (@ox_lib/imports/callback/server.lua:96)
[  script:r_moneywash] 

could you help me ??

**Comment by rumaier** [comment]
> ![Screenshot (4)](https://private-user-images.githubusercontent.com/95373009/377090948-9b9dc1ed-dcd1-4d14-b523-66431a77d2a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTczMzcsIm5iZiI6MTcyOTA5NzAzNywicGF0aCI6Ii85NTM3MzAwOS8zNzcwOTA5NDgtOWI5ZGMxZWQtZGNkMS00ZDE0LWI1MjMtNjY0MzFhNzdkMmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE2NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMjMxNWFhN2ZlZTk1Y2IwMmM0M2U3N2I1NjYxZjM1MGY0MjRhNDQ5OTUxYzkyNWNkOTM3MjBlMmE3OTE0ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G2v5ETvStncDupCfv1AQFlW4YvSWMLSlRZIF_YifTvY) ![Screenshot (5)](https://private-user-images.githubusercontent.com/95373009/377090988-76805fbc-86b9-471a-82f8-dbfc16652ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTczMzcsIm5iZiI6MTcyOTA5NzAzNywicGF0aCI6Ii85NTM3MzAwOS8zNzcwOTA5ODgtNzY4MDVmYmMtODZiOS00NzFhLTgyZjgtZGJmYzE2NjUyZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE2NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OWM5N2ZiMTIzNjNkMDkxOTQ2MThiNGY4NDZiMmY0ZjI3NmNlY2RlYjdiMWNhN2ViYzU1ODU2OTVhMThiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sf8RFAu3X73Q2snAEUTZL1WZHPk13GUDvaWx-lBSDus) [ script:r_moneywash] r_moneywash:getPlayerCooldown [ script:r_moneywash] SCRIPT ERROR: @r_moneywash/src/server/main.lua:9: attempt to index a nil value (field 'Inventory') [ script:r_moneywash] > callbackResponse (@ox_lib/imports/callback/server.lua:79) [ script:r_moneywash] > handler (@ox_lib/imports/callback/server.lua:96) [ script:r_moneywash]
> 
> could you help me ??

Open a ticket in our Discord for support please.
